/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:79148891-9869-47cd-ac9e-33ff792f9dc9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_2y8jltFgn",
    "aws_user_pools_web_client_id": "4lpscacneh13lue4mq0nj316iu",
    "oauth": {}
};


export default awsmobile;
